version: "3.7"
services:
  icarus:
    container_name: icarus-server
    hostname: icarus-server
    image: ghcr.io/studyfranco/icarus-server:master
    #network_mode: "host"
    volumes:
      - "/path/to/config:/config"
    ports:
      - 17777:17777/udp
      - 27015:27015/udp
    expose:
      - 8211/udp
      - 27015/udp
    environment:
      - "SERVER_NAME=IcarusServerByMe"
      - "SERVER_PORT=17777"
      - "SERVER_QUERY_PORT=27015"
      - "MAXPLAYERS=32"
      - "SERVERPASSWORD=password"
      - "SERVERADMINPASSWORD=password"
      - "PUID=2198"
      - "PGID=2198"
      - SHUTDOWN_NOT_JOINED_FOR=-1
      - SHUTDOWN_EMPTY_FOR=-1
      - ALLOW_NON_ADMINS_LAUNCH="True"
      - ALLOW_NON_ADMINS_DELETE="False"
      - LOAD_PROSPECT=""
      - CREATE_PROSPECT=""
      - RESUME_PROSPECT="True"
      - STEAM_ASYNC_TIMEOUT=60
      - BRANCH="public"
      - "TZ=Etc/UTC"
    tmpfs:
      - "/run:exec,mode=777"
      - "/tmp:exec,mode=777"
      - "/tmp/dumps:exec,mode=777"
      - "/var/tmp:exec,mode=777"
      #- "/config/gamefiles/steamapps/temp:uid=2198,gid=2198"
    restart: "unless-stopped"